manifest:
  remotes:
    - name: suriaribeiro
      url-base: https://github.com/suriaribeiro
  projects:
    - name: zmk
      remote: suriaribeiro
      revision: main
      import: app/west.yml
  self:
    path: config
